# Generated by Django 3.0.8 on 2020-08-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='emaol',
            new_name='email',
        ),
    ]
